== Attribution

Based on "link:https://github.com/KhronosGroup/Vulkan-Tutorial[The Khronos Vulkan^®^ Tutorial]", which is based on the "link:https://vulkan-tutorial.com/[Vulkan Tutorial]" by Alexander Overvoorde licensed under link:https://creativecommons.org/licenses/by-sa/4.0/[CC BY-SA 4.0].

== About

Trying different stuffs on different branches.

Just practicing C++, Vulkan, and repo structuring.

Applied VMA on chapter 21, index buffer.

Added uniform buffer.

Added texture sampler. (stb loader)

== Project Structure

single cpp, shader, assets, CMakeLists.txt.

assets and compiled shader are copied to build.

== Installation Dependencies

Vulkan, glfw3, glm, stb.

== Build

To use vcpkg, remove .bak extension from vcpkg*.bak files
[source]
----
cmake --preset default
cmake --build build
----

Check build/base_render/base_render. launch the executable on the parent directory of `shader`.

Can just launch sln when using Visual Studio.

== License

All licensed as
https://creativecommons.org/publicdomain/zero/1.0/[CC0 1.0 Universal], same as Vulkan Tutorial attachments/